--- 
ReportDefinitions: 
  - 
    moduleName: rainmaker-pension
    query: "select application_number,name as applicantName, date_of_retirement , workflow_state from eg_pension_workflow_header pwr join public.eg_pension_employee pe on pwr.pension_employee_id=pe.uuid where 1=1 AND pwr.workflow_type='RRP_SERVICE'"
    reportName: RegularNormalPension
    searchParams: 
      - 
        isMandatory: true
        label: reports.rainmaker-pgr.datefrom
        name: fromDate
        searchClause: "AND pwr.application_date >= $fromDate"
        source: eg_pension_workflow_header
        type: epoch
      - 
        isMandatory: true
        label: reports.rainmaker-pgr.dateto
        name: toDate
        searchClause: "AND pwr.application_date <= $toDate"
        source: eg_pension_workflow_header
        type: epoch
    sourceColumns: 
      - 
        label: PENSION_APPLICATION_NUMBER
        name: application_number
        source: eg_pension_workflow_header
        type: string
      - 
        label: "Applicant Name"
        name: applicantName
        source: eg_pension_workflow_header
        type: string
      - 
        label: PENSION_DOR
        name: date_of_retirement
        source: eg_pension_workflow_header
        type: epoch
      - 
        label: State
        name: workflow_state
        source: eg_pension_workflow_header
        type: string
  - 
    moduleName: rainmaker-pension
    query: "select cast(TRIM (LEADING '0' FROM	CAST (pp.pensioner_number AS TEXT)) as integer) as pensioner_number, (case when pd.name is null or pd.name = '' then pe.name else pd.name end) as name,  fma, miscellaneous, over_payment, income_tax, cess, basic_pension, additional_pension, commuted_pension, net_deductions, final_calculated_pension, interim_relief, da, total_pension, pension_deductions, wound_extraordinary_pension, attendant_allowance, ltc from eg_pension_revision pr join eg_pension_pensioner pp on pr.pensioner_id=pp.uuid join eg_pension_employee pe on pp.pension_employee_id=pe.uuid left join eg_pension_dependent pd on pd.pension_employee_id = pp.pension_employee_id  and pd.active=true where 1=1 AND pp.active=true AND pr.active=true"
    reportName: PensionObligation
    searchParams: 
      - 
        isMandatory: true
        label: Year
        name: Year
        pattern: "list://2020:2020,2021:2021,2022:2022,2023:2023,2024:2024,2025:2025"
        searchClause: "and ((cast(concat($Year, lpad($Month,2,'0')) as integer)>=
cast(concat(cast(pr.effective_start_year as varchar)
, lpad(cast(pr.effective_start_month as varchar),2,'0')) as integer)
and pr.effective_end_year is not null 
and pr.effective_end_month is not null
and cast(concat($Year, lpad($Month,2,'0')) as integer)<=
cast(concat(cast(pr.effective_end_year 
as varchar), lpad(cast(pr.effective_end_month as varchar),2,'0')) as integer
))"
        source: eg_pension_revision
        type: singlevaluelist
        wrapper: true
      - 
        isMandatory: true
        label: Month
        name: Month
        pattern: "list://1:1,2:2,3:3,4:4,5:5,6:6,7:7,8:8,9:9,10:10,11:11,12:12"
        searchClause: "or (cast(concat($Year, lpad($Month,2,'0')) as integer)>=
cast(concat(cast(pr.effective_start_year as varchar)
, lpad(cast(pr.effective_start_month as varchar),2,'0')) as integer)
and pr.effective_end_year is null and pr.effective_end_month is null)) order by cast(TRIM (LEADING '0' FROM	CAST (pp.pensioner_number AS TEXT)) as integer)"
        source: eg_pension_revision
        type: singlevaluelist
        wrapper: true
    sourceColumns: 
      - 
        label: "PPO"
        name: pensioner_number
        source: eg_pension_pensioner
        total: false
        type: string
      - 
        label: "Name"
        name: name
        source: eg_pension_employee
        total: false
        type: string
      - 
        label: "BP"
        name: basic_pension
        source: eg_pension_revision
        total: true
        type: string
      - 
        label: "Adl_Pen"
        name: additional_pension
        source: eg_pension_revision
        total: true
        type: string
      - 
        label: "IR"
        name: interim_relief
        source: eg_pension_revision
        total: true
        type: string
      - 
        label: "LTC"
        name: ltc
        source: eg_pension_revision
        total: true
        type: string
      - 
        label: "-CP"
        name: commuted_pension
        source: eg_pension_revision
        total: true
        type: string
      - 
        label: "DA"
        name: da
        source: eg_pension_revision
        total: true
        type: string
      - 
        label: "MA"
        name: fma
        source: eg_pension_revision
        total: true
        type: string
      - 
        label: "MISC"
        name: miscellaneous
        source: eg_pension_revision
        total: true
        type: string
      - 
        label: "-OVP"
        name: over_payment
        source: eg_pension_revision
        total: true
        type: string
      - 
        label: "TOTAL"
        name: total_pension
        source: eg_pension_revision
        total: true
        type: string
      - 
        label: "NETPAY"
        name: final_calculated_pension
        source: eg_pension_revision
        total: true
        type: string
  - 
    
    moduleName: rainmaker-pension
    query: "select pp.pensioner_number as pensioner_number , pe.name as name
, final_calculated_pension,
(case when pd.name is null or pd.name = '' then ppad.bank_address else pd.bank_details end) as bank_details,
(case when pd.name is null or pd.name = '' then ppad.bank_code else pd.bank_code end) as bank_code,
(case when pd.name is null or pd.name = '' then ppad.bank_ifsc else pd.bank_ifsc end) as bank_ifsc,
(case when pd.name is null or pd.name = '' then ppad.account_number else pd.bank_account_number end) as bank_account_number
from eg_pension_revision pr join eg_pension_pensioner pp on pr.pensioner_id=pp.uuid join eg_pension_employee pe on pp.pension_employee_id=pe.uuid  
join eg_pension_pensioner_application_details ppad 
on ppad.pensioner_id = pp.uuid 
left join eg_pension_dependent pd on pd.pension_employee_id = pp.pension_employee_id
AND pp.active=true AND pr.active=true where 1=1"
    reportName: MonthlyPensionDrawn
    searchParams: 
      - 
        isMandatory: true
        label: Year
        name: Year
        pattern: "list://2020:2020,2021:2021,2022:2022,2023:2023,2024:2024,2025:2025"
        searchClause: "and cast(concat($Year, lpad($Month,2,'0')) as integer)>=
cast(concat(cast(pr.effective_start_year as varchar), lpad(cast(pr.effective_start_month as varchar),2,'0')) as integer)"
        source: eg_pension_revision
        type: singlevaluelist
        wrapper: true
      - 
        isMandatory: true
        label: Month
        name: Month
        pattern: "list://1:1,2:2,3:3,4:4,5:5,6:6,7:7,8:8,9:9,10:10,11:11,12:12"
        searchClause: "and (
pr.effective_end_year is not null and pr.effective_end_month is not null
and cast(concat($Year, lpad($Month,2,'0')) as integer)<
cast(concat(cast(pr.effective_end_year as varchar), lpad(cast(pr.effective_end_month as varchar),2,'0')) as integer)
or
(pr.effective_end_year is null and pr.effective_end_month is null)
)"
        source: eg_pension_revision
        type: singlevaluelist
        wrapper: true
    sourceColumns: 
      - 
        label: "Pensioner Number"
        name: pensioner_number
        source: eg_pension_pensioner
        total: false
        type: string
      - 
        label: "Pensioner Name"
        name: name
        source: eg_pension_employee
        total: false
        type: string
      - 
        label: "Net Pension"
        name: final_calculated_pension
        source: eg_pension_revision
        total: true
        type: string
      - 
        label: "Bank Name"
        name: bank_details
        source: eg_pension_revision
        total: false
        type: string
      - 
        label: "Bank IFSC"
        name: bank_ifsc
        source: eg_pension_revision
        total: false
        type: string
      - 
        label: "Bank Code"
        name: bank_code
        source: eg_pension_revision
        total: false
        type: string
      - 
        label: "Bank Account Number"
        name: bank_account_number
        source: eg_pension_revision
        total: false
        type: string


  - 
    moduleName: rainmaker-pension
    query: "select application_number,name as applicantName, date_of_retirement, workflow_state from eg_pension_workflow_header pwr join public.eg_pension_employee pe on pwr.pension_employee_id=pe.uuid where 1=1 AND pwr.workflow_type='DOE_SERVICE'"
    reportName: DeathOfAnEmployee
    searchParams: 
      - 
        isMandatory: true
        label: reports.rainmaker-pgr.datefrom
        name: fromDate
        searchClause: "AND pwr.application_date >= $fromDate"
        source: eg_pension_workflow_header
        type: epoch
      - 
        isMandatory: true
        label: reports.rainmaker-pgr.dateto
        name: toDate
        searchClause: "AND pwr.application_date <= $toDate"
        source: eg_pension_workflow_header
        type: epoch
    sourceColumns: 
      - 
        label: PENSION_APPLICATION_NUMBER
        name: application_number
        source: eg_pension_workflow_header
        type: string
      - 
        label: "Applicant Name"
        name: applicantName
        source: eg_pension_workflow_header
        type: string
      - 
        label: PENSION_DOR
        name: date_of_retirement
        source: eg_pension_workflow_header
        type: epoch
      - 
        label: State
        name: workflow_state
        source: eg_pension_workflow_header
        type: string
  - 
    moduleName: rainmaker-pension
    query: "select application_number,name as applicantName, date_of_retirement, workflow_state from eg_pension_workflow_header pwr join public.eg_pension_employee pe on pwr.pension_employee_id=pe.uuid where 1=1 AND pwr.workflow_type='DOP_SERVICE'"
    reportName: DeathOfPensioner
    searchParams: 
      - 
        isMandatory: true
        label: reports.rainmaker-pgr.datefrom
        name: fromDate
        searchClause: "AND pwr.application_date >= $fromDate"
        source: eg_pension_workflow_header
        type: epoch
      - 
        isMandatory: true
        label: reports.rainmaker-pgr.dateto
        name: toDate
        searchClause: "AND pwr.application_date <= $toDate"
        source: eg_pension_workflow_header
        type: epoch
    sourceColumns: 
      - 
        label: PENSION_APPLICATION_NUMBER
        name: application_number
        localisationRequired: false
        source: eg_pension_workflow_header
        type: string
      - 
        label: "Applicant Name"
        name: applicantName
        localisationRequired: false
        source: eg_pension_workflow_header
        type: string
      - 
        label: PENSION_DOR
        name: date_of_retirement
        localisationRequired: false
        source: eg_pension_workflow_header
        type: epoch
      - 
        label: State
        name: workflow_state
        localisationRequired: true
        source: eg_pension_workflow_header
        type: string
  - 
    moduleName: rainmaker-pension
    query: "select pe.id, pe.code as code , u.name as name , u.gender as gender , pe.employeetype as employee_type  , u.dob ,pe.dateofsuperannuation as dateofsuperannuation   from eg_hrms_employee pe  join eg_user u  on pe.uuid=u.uuid  WHERE 1=1"
    reportName: EmployeeToBeRetired
    searchParams: 
      - 
        isMandatory: true
        label: reports.rainmaker-pgr.datefrom
        name: fromDate
        searchClause: "AND pe.dateofsuperannuation >= $fromDate"
        source: eg_hrms_employee
        type: epoch
      - 
        isMandatory: true
        label: reports.rainmaker-pgr.dateto
        name: toDate
        searchClause: "AND pe.dateofsuperannuation <= $toDate"
        source: eg_hrms_employee
        type: epoch
    sourceColumns: 
      - 
        label: PENSION_EMPLOYEE_CODE
        name: code
        source: eg_hrms_employee
        type: string
      - 
        label: PENSION_EMPLOYEE_NAME
        name: name
        source: eg_user
        type: string
      - 
        label: PENSION_EMPLOYEE_TYPE
        name: employee_type
        source: eg_user
        total: false
        type: string
      - 
        label: PENSION_DOB
        name: dob
        source: eg_user
        total: false
        type: epoch
      - 
        label: PENSION_DOR
        name: dateofsuperannuation
        source: eg_hrms_employee
        total: false
        type: epoch
